E comments
simplic/simplic-package pull request #9
Opened 2021-09-02 10:19 UTC by MEichhoff

2021-09-02 11:03 UTC, simplicbe approved these changes

2021-09-06 11:12 UTC, simplicbe requested changes

2021-09-06 11:12 UTC, simplicbe commented on src/Simplic.Package.Data.DB/InitializePackageSystemRepository.cs
> +        /// Checks wherther the table already exists.
`wherther` -> `whether`

2021-09-06 12:11 UTC, MEichhoff commented on src/Simplic.Package.Data.DB/InitializePackageSystemRepository.cs
> +        /// Checks wherther the table already exists.
```suggestion
        /// Checks whether the table already exists.
```

2021-09-20 19:58 UTC, simplicbe approved these changes

2021-09-22 11:17 UTC, merged